# Generated by Django 6.1.2 on 2026-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='OPIS Truckstop ID from the source CSV.', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(default='US', max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Geocoded'), ('failed', 'Not found')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_fuelst_state_99cf3a_idx'), models.Index(fields=['retail_price'], name='fuel_fuelst_retail__3784a3_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_fuelst_latitud_e7de73_idx'), models.Index(fields=['geocode_status'], name='fuel_fuelst_geocode_4ae95b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='fuelstation_price_positive')],
            },
        ),
    ]
